"""Lazy dataset for OSCAR.

Each data directory corresponds to one ultrasound sweep (subject/scan) and must
contain:

    images.npy            [N, H, W]  uint8  B-mode frames
    poses_labels.npy      [N, w, h, 3]      per-pixel 3D coordinates in [0, 1]
    masks_gt.npy          [N, H, W]  uint8  per-frame occupancy mask (supervision)
    point_cloud_min_max.txt                 physical extent (for voxel spacing)
    gt_volume.npy         [G, G, G]  uint8  GT 3D occupancy volume (for metrics)

``poses_labels`` are the 3D points obtained by ray-marching each frame's pixels
from ``poses.npy`` (see ``scripts/create_poses_labels.py``); OSCAR queries the
network directly at these points, so the dataset never needs ``poses.npy`` or
on-the-fly ray generation. Only the small ``poses.npy`` is distributed --
``poses_labels.npy``, ``point_cloud_min_max.txt`` and ``gt_volume.npy`` are
regenerated by the preprocessing scripts.

Large arrays are memory-mapped. One latent code is associated with each unique
directory name.
"""

import os

import cv2
import numpy as np


class UltrasoundLazyDataset:
    def __init__(self, datadirs, mmap_mode=None):
        if isinstance(datadirs, str):
            datadirs = [datadirs]
        self.datadirs = [d.strip() for d in datadirs]
        self.mmap_mode = mmap_mode

        self._images = []          # list of [N, H, W]
        self._poses_labels = []    # list of [N, w, h, 3]
        self._masks_gt = []        # list of [N, H, W]
        self._voxel_spacing = []   # list of [3] (mm)
        self._lengths = []

        names = []
        for d in self.datadirs:
            dataset_id = os.path.basename(d.rstrip("/"))

            self._images.append(np.load(os.path.join(d, "images.npy"), mmap_mode=self.mmap_mode))
            self._poses_labels.append(np.load(os.path.join(d, "poses_labels.npy"), mmap_mode=self.mmap_mode))

            masks_gt_path = os.path.join(d, "masks_gt.npy")
            if os.path.exists(masks_gt_path):
                self._masks_gt.append(np.load(masks_gt_path, mmap_mode=self.mmap_mode))
            else:
                self._masks_gt.append(np.zeros_like(self._images[-1]))

            with open(os.path.join(d, "point_cloud_min_max.txt"), "r") as f:
                lines = f.readlines()
                min_pt = np.array([float(x) for x in lines[0].split(":")[1].strip()[1:-1].split(",")])
                max_pt = np.array([float(x) for x in lines[1].split(":")[1].strip()[1:-1].split(",")])
                self._voxel_spacing.append((max_pt - min_pt) / 128.0)  # 128^3 grid

            n = self._images[-1].shape[0]
            self._lengths.append(n)
            names.extend([dataset_id] * n)

        self.dataset_names = np.array(names)
        _, idx = np.unique(self.dataset_names, return_index=True)
        uniq = self.dataset_names[np.sort(idx)]
        self.dataset_names_to_ids = {name: i for i, name in enumerate(uniq)}
        self._latent_ids = np.array([self.dataset_names_to_ids[n] for n in self.dataset_names], dtype=int)

        self._offsets = np.cumsum([0] + self._lengths[:-1])
        self.i_train = np.arange(len(self), dtype=int)

    def __len__(self):
        return int(np.sum(self._lengths))

    def _which_dataset(self, global_idx):
        k = int(np.searchsorted(self._offsets, global_idx + 1) - 1)
        return k, global_idx - self._offsets[k]

    def __getitem__(self, idx):
        k, j = self._which_dataset(idx)

        img = self._images[k][j].astype(np.float32) / 255.0   # [H, W] in [0, 1]
        pts = self._poses_labels[k][j].astype(np.float32)     # [w, h, 3] in [0, 1]
        msk = self._masks_gt[k][j].astype(np.float32)         # [H, W] in {0, 1}

        # Align mask to image (some sweeps store the mask transposed).
        if msk.shape != img.shape:
            msk = np.transpose(msk)
            if msk.shape != img.shape:
                raise ValueError(f"Mask shape {msk.shape} does not match image shape {img.shape}")

        # Resize the image to the per-pixel coordinate grid if they differ.
        if img.shape[0] != pts.shape[1] or img.shape[1] != pts.shape[0]:
            h, w = pts.shape[1], pts.shape[0]
            img = cv2.resize(img, (w, h), interpolation=cv2.INTER_LINEAR)

        return {
            "image": img,                                  # [H, W]
            "poses_labels": pts,                           # [w, h, 3]
            "mask_gt": msk,                                # [H, W]
            "dataset_name": self.dataset_names[idx],
            "latent_id": int(self._latent_ids[idx]),
            "voxel_spacing": self._voxel_spacing[k],       # [3] in mm
        }

    def get_gt_volume(self, latent_id, gt_volume_name="gt_volume.npy"):
        """Load the GT 3D occupancy volume for the subject with this latent id."""
        dataset_name = next((n for n, lid in self.dataset_names_to_ids.items() if lid == latent_id), None)
        if dataset_name is None:
            raise ValueError(f"No dataset found for latent_id={latent_id}")
        datadir = next((d for d in self.datadirs if os.path.basename(d.rstrip("/")) == dataset_name), None)
        if datadir is None:
            raise FileNotFoundError(f"Could not find data directory for dataset '{dataset_name}'")
        gt_npy = os.path.join(datadir, gt_volume_name)
        if not os.path.exists(gt_npy):
            raise FileNotFoundError(f"GT volume not found at {gt_npy}")
        return np.load(gt_npy).astype(np.uint8)
